# Generated by Django 5.0.2 on 2024-03-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte'), ('alojamiento', 'Alojamiento'), ('actividades', 'Actividades Turísticas'), ('alimentacion', 'Alimentación'), ('gastos', 'Gastos Diversos')], max_length=50)),
            ],
        ),
    ]
